<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>lv.cebbys.tools</groupId>
    <artifactId>ghidra-bom-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <description>Parent project for Ghidra BOM and test modules</description>

    <modules>
        <module>ghidra-bom</module>
        <module>ghidra-bom-test</module>
    </modules>
</project>