name: Validate Release Branch CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [release/**]

  push:
    branches: [release/**]
jobs:
  setup-and-verify:
    runs-on: ubuntu-latest

    steps:
      # 1. Essential: Checkout the repository so the runner sees your scripts
      - name: Checkout Repository
        uses: actions/checkout@v6

      # 2. Run your local action
      - name: Setup Ghidra
        id: ghidra-setup
        uses: ./.github/actions/setup-ghidra-action
        with:
          ghidra-version: "12.0"

      - name: Verify Output Path
        shell: bash
        run: |
          echo "Ghidra is installed at: ${{ steps.ghidra-setup.outputs.ghidra-home-path }}"
          # Check if the folder exists at that absolute path
          ls -d "${{ steps.ghidra-setup.outputs.ghidra-home-path }}"

      # # 3. Final Verification (Individual Step)
      # - name: Check Ghidra Executable
      #   run: |
      #       if [ -f ".ghidra/ghidraRun" ]; then
      #         echo "Success: Ghidra executable found."
      #       else
      #         echo "Error: Ghidra executable missing!"
      #         exit 1
      #       fi
