name: Validate Release Branch CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [release/**]
  push:
    branches: [release/**]

jobs:
  setup-and-verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra-version: ["12.0", "11.4.3", "10.4"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Ghidra
        id: ghidra-setup
        uses: ./.github/actions/setup-ghidra-action
        with:
          ghidra-version: ${{ matrix.ghidra-version }}
